# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rgb_color = QtWidgets.QPushButton(self.centralwidget)
        self.rgb_color.setGeometry(QtCore.QRect(30, 400, 181, 91))
        self.rgb_color.setObjectName("rgb_color")
        self.bgr_color = QtWidgets.QPushButton(self.centralwidget)
        self.bgr_color.setGeometry(QtCore.QRect(480, 400, 181, 91))
        self.bgr_color.setObjectName("bgr_color")
        self.gray_color = QtWidgets.QPushButton(self.centralwidget)
        self.gray_color.setGeometry(QtCore.QRect(260, 400, 171, 91))
        self.gray_color.setObjectName("gray_color")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(30, 30, 631, 351))
        self.image.setText("")
        self.image.setObjectName("image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rgb_color.setText(_translate("MainWindow", "RGB COLOR"))
        self.bgr_color.setText(_translate("MainWindow", "BGR COLOR"))
        self.gray_color.setText(_translate("MainWindow", "GRAY"))
