# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooser.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(20, 10, 631, 351))
        self.image.setText("")
        self.image.setObjectName("image")
        self.mcqueen = QtWidgets.QPushButton(self.centralwidget)
        self.mcqueen.setGeometry(QtCore.QRect(20, 380, 181, 91))
        self.mcqueen.setObjectName("mcqueen")
        self.optimus = QtWidgets.QPushButton(self.centralwidget)
        self.optimus.setGeometry(QtCore.QRect(470, 380, 181, 91))
        self.optimus.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle("Image Chooser")
        self.mcqueen.setText(_translate("MainWindow", "McQueen"))
        self.optimus.setText(_translate("MainWindow", "Optimus Prime"))
